export const DEFAULT_CONFIG = Object.freeze({
  daysPerYear: 360,
  waterLevel: 0.28,
  foodRegrowthPerDay: 0.045,
  vegetationRegrowthPerDay: 0.006,
  hungerPerDay: 0.012,
  hungryThreshold: 0.35,
  starvationThreshold: 0.9,
  starvationDamagePerDay: 0.025,
  recoveryPerDay: 0.004,
  passiveMoveChance: 0.18,
  eatAmount: 0.58,
  foodPerMeal: 0.65,
  adultAgeYears: 18,
  femaleFertilityEndYears: 45,
  birthChancePerEligiblePairPerDay: 0.0010,
  birthCooldownDays: 300,
  oldAgeYears: 75,
  hardMaxAgeYears: 105,
  maxEventHistory: 2500,
  settlementCheckIntervalDays: 30,
  settlementMinAdults: 4,
  settlementFormationDays: 90,
  settlementMinSpacing: 6,
  settlementMembershipRadius: 3,
  settlementHomeBiasChance: 0.05,
  settlementAbandonmentDays: 360,
  settlementTerritoryRadius: 3,
  grazerHungerPerDay: 0.006,
  grazerHungryThreshold: 0.35,
  grazerMinimumEdibleVegetation: 0.2,
  grazerVegetationPerMeal: 0.8,
  grazerEatAmount: 0.58,
  grazerStarvationThreshold: 0.9,
  grazerStarvationDamagePerDay: 0.025,
  grazerRecoveryPerDay: 0.004,
  grazerPassiveMoveChance: 0.12,
  grazerBirthChancePerEligiblePairPerDay: 0
});

export function mergeConfig(overrides = {}) {
  return { ...DEFAULT_CONFIG, ...overrides };
}
